name: Deploy to Production
on: workflow_dispatch
jobs:
    deploy_next:
        name: Build and deploy Next.js app
        runs-on: ubuntu-latest
        environment: Production
        concurrency: Production
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Get latest tag
              id: latest_tag
              uses: davidspek/gha-get-docker-hub-tags@0.1.15
              with:
                  img: "ghcr.io/streamlux/pulsebanner-next" # container image to list tags from

            # Optionally check the tag we got back
            - name: Check outputs
              run: |
                  echo "Latest Image Tag - ${{ steps.latest_tag.outputs.latest_tag }}"
                  echo "Next Major Tag - ${{ steps.latest_tag.outputs.new_major }}"
                  echo "Next Minor Tag - ${{ steps.latest_tag.outputs.new_minor }}"
                  echo "Next Patch Tag - ${{ steps.latest_tag.outputs.new_patch }}"
                  echo "Next Major Tag with v prefix - ${{ steps.latest_tag.outputs.new_v_major }}"
                  echo "Next Minor Tag with v prefix - ${{ steps.latest_tag.outputs.new_v_minor }}"
                  echo "Next Patch Tag with v prefix - ${{ steps.latest_tag.outputs.new_v_patch }}"
