name: Deploy to Production
on: workflow_dispatch
jobs:
    deploy_next:
        name: Build and deploy Next.js app
        runs-on: ubuntu-latest
        environment: Production
        concurrency: Production
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Get latest tag
              id: latest_tag
              uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.3
              with:
                  org: "streamlux" # Docker Hub user or organisation name
                  repo: "pulsebanner-next" # Docker Hub repository name

            # Optionally check the tag we got back
            - name: Check outputs
              run: |
                  echo "Latest Image Tag - ${{ steps.latest_tag.outputs.tag }}"
