name: Build Next.js app
# This workflow is triggered on pushes to the repository.
on:
    push:
        paths-ignore:
            - "apps/remotion/**"

jobs:
    build:
        name: Docker build
        environment: Staging
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Install and cache dependencies
              uses: bahmutov/npm-install@v1

            - name: "nx run next:make:ci"
              run: npx nx run next:make:ci
              env:
                  INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}

            - name: "prisma migrate deploy"
              run: npx prisma migrate deploy
              env:
                  DB_URL: ${{ secrets.DB_URL }}
