name: Deploy Next.js app
# This workflow is triggered on pushes to the repository.
on:
    push:
        paths-ignore:
            - "apps/remotion/**"

jobs:
    build:
        name: Docker build
        environment: Staging
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v3
              with:
                  # list of Docker images to use as base name for tags
                  images: |
                      ghcr.io/streamlux/pulsebanner-remotion
                  # generate Docker tags based on the following events/attributes
                  tags: |
                      type=sha,prefix={{branch}}-,priority=10000
                      type=sha
                      type=schedule
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Install and cache dependencies
              uses: bahmutov/npm-install@v1

            - name: "nx run next:make:ci"
              run: npx nx run next:make:ci
              env:
                  INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  file: "apps/next/Dockerfile"
                  context: "."
                  platforms: linux/amd64
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            - name: "prisma migrate deploy"
              run: npx prisma migrate deploy
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}

            - name: "Deploy to Caprover"
              uses: addnab/docker-run-action@v3
              env:
                  CAPROVER_APP_TOKEN: ${{ secrets.NEXT_CAPROVER_APP_TOKEN }}
                  APP_URL: ${{ secrets.CAPROVER_URL }}
                  APP_NAME: ${{ secrets.NEXT_APP_NAME }}
                  IMAGE_NAME: ${{ fromJson(steps.meta.outputs.json).tags[0] }}
              with:
                  image: caprover/cli-caprover:v2.2.3
                  run: "caprover deploy --caproverUrl $CAPROVER_URL --imageName $IMAGE_NAME --appName $APP_NAME"
