name: Build remotion server

on:
    push:
        paths-ignore:
            - 'apps/next/**'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: 'Build remotion app'
              run: npm i ts-node

            - name: 'Build remotion app'
              run: npx ts-node apps/remotion/scripts/build.ts

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: 'dist/apps/remotion'
                  platforms: linux/amd64
                  push: true
                  tags: |
                      "ghcr.io/streamlux/pulsebanner-remotion:latest"
