name: remotion image ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Generate package.json'
        run: npx nx run remotion:deps

      - name: 'Copy files to dist'
        run: npx nx run remotion:build

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: 'dist/apps/remotion'
          platforms: linux/amd64
          push: true
          tags: |
            "ghcr.io/streamlux/remotion-server:latest"
